name = "bépo"
author = "Frédéric Boiteux"
language = "French"
link = "bepo.fr"
year = 2008

[formats.standard]
matrix = [["b", "é", "p", "o", "è", "^", "v", "d", "l", "j", "z", "w"],
["a", "u", "i", "e", ",", "c", "t", "s", "r", "n", "m", "ç"],
["à", "y", "x", ".", "k", ",", "q", "g", "h", "f"]]

map = {}
home_row = 1
